name:                calc-lang
version:             1.0.0
github:              "severij/calc-lang"
license:             MIT
author:              "Severi Jääskeläinen"
maintainer:          "severij@tuta.io"
copyright:           "2019 Severi Jääskeläinen"

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/severij/calc-lang#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- parser-combinators
- megaparsec

library:
  source-dirs: src

executables:
  calc-lang-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - calc-lang
